use super::types::{
    AppStyleOverride, ArtifactKind, ContextFamily, Density, Formality, ListBehavior, MarkupPolicy,
};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ReleaseTier {
    Reference,
    Extended,
    Fallback,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TitleMarkerDefinition {
    pub suffix: String,
    pub required_host_suffix: Option<String>,
    pub required_native_identity: Option<String>,
}

impl TitleMarkerDefinition {
    fn for_host(suffix: &str, required_host_suffix: &str) -> Self {
        Self {
            suffix: suffix.to_string(),
            required_host_suffix: Some(required_host_suffix.to_string()),
            required_native_identity: None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProfileDefinition {
    pub id: String,
    pub family: ContextFamily,
    pub app_label: String,
    pub icon_key: String,
    pub override_id: Option<String>,
    pub exact_hosts: Vec<String>,
    pub host_suffixes: Vec<String>,
    pub native_identities: Vec<String>,
    pub process_aliases: Vec<String>,
    pub title_markers: Vec<TitleMarkerDefinition>,
    pub release_tier: ReleaseTier,
}

impl ProfileDefinition {
    #[allow(clippy::too_many_arguments)]
    fn new(
        id: &str,
        family: ContextFamily,
        app_label: &str,
        icon_key: &str,
        override_id: Option<&str>,
        exact_hosts: &[&str],
        host_suffixes: &[&str],
        native_identities: &[&str],
        process_aliases: &[&str],
        release_tier: ReleaseTier,
    ) -> Self {
        Self {
            id: id.to_string(),
            family,
            app_label: app_label.to_string(),
            icon_key: icon_key.to_string(),
            override_id: override_id.map(str::to_string),
            exact_hosts: strings(exact_hosts),
            host_suffixes: strings(host_suffixes),
            native_identities: strings(native_identities),
            process_aliases: strings(process_aliases),
            title_markers: Vec::new(),
            release_tier,
        }
    }

    fn with_title_marker(mut self, marker: TitleMarkerDefinition) -> Self {
        self.title_markers.push(marker);
        self
    }
}

fn strings(values: &[&str]) -> Vec<String> {
    values.iter().map(|value| (*value).to_string()).collect()
}

#[allow(clippy::too_many_arguments)]
fn reference(
    id: &str,
    family: ContextFamily,
    label: &str,
    icon: &str,
    override_id: Option<&str>,
    exact_hosts: &[&str],
    host_suffixes: &[&str],
    native_ids: &[&str],
    process_aliases: &[&str],
) -> ProfileDefinition {
    ProfileDefinition::new(
        id,
        family,
        label,
        icon,
        override_id,
        exact_hosts,
        host_suffixes,
        native_ids,
        process_aliases,
        ReleaseTier::Reference,
    )
}

#[allow(clippy::too_many_arguments)]
fn extended(
    id: &str,
    family: ContextFamily,
    label: &str,
    icon: &str,
    exact_hosts: &[&str],
    host_suffixes: &[&str],
    native_ids: &[&str],
    process_aliases: &[&str],
) -> ProfileDefinition {
    ProfileDefinition::new(
        id,
        family,
        label,
        icon,
        None,
        exact_hosts,
        host_suffixes,
        native_ids,
        process_aliases,
        ReleaseTier::Extended,
    )
}

pub fn builtin_profile_definitions() -> Vec<ProfileDefinition> {
    use ContextFamily::*;

    vec![
        reference(
            "email.gmail",
            Email,
            "Gmail",
            "gmail",
            Some("gmail"),
            &["mail.google.com"],
            &[],
            &[],
            &[],
        ),
        reference(
            "email.outlook",
            Email,
            "Outlook",
            "outlook",
            Some("outlook"),
            &["outlook.office.com", "outlook.live.com"],
            &[],
            &["com.microsoft.outlook"],
            &["outlook.exe"],
        ),
        reference(
            "email.apple_mail",
            Email,
            "Apple Mail",
            "apple-mail",
            None,
            &[],
            &[],
            &["com.apple.mail"],
            &["mail"],
        ),
        reference(
            "chat.slack",
            WorkChat,
            "Slack",
            "slack",
            Some("slack"),
            &["app.slack.com"],
            &["slack.com"],
            &["com.tinyspeck.slackmacgap"],
            &["slack", "slack.exe"],
        ),
        reference(
            "chat.teams",
            WorkChat,
            "Microsoft Teams",
            "teams",
            Some("teams"),
            &["teams.microsoft.com"],
            &[],
            &["com.microsoft.teams", "com.microsoft.teams2"],
            &["ms-teams.exe", "teams.exe"],
        ),
        reference(
            "chat.lark",
            WorkChat,
            "Lark",
            "lark",
            Some("lark"),
            &[],
            &["larksuite.com", "feishu.cn"],
            &["com.larksuite.suite", "com.bytedance.feishu"],
            &["lark", "feishu", "lark.exe", "feishu.exe"],
        ),
        reference(
            "chat.dingtalk",
            WorkChat,
            "DingTalk",
            "dingtalk",
            None,
            &[],
            &[],
            &["com.alibaba.dingtalkmac"],
            &["dingtalk", "dingtalk.exe"],
        ),
        reference(
            "chat.wecom",
            WorkChat,
            "WeCom",
            "wecom",
            None,
            &["work.weixin.qq.com"],
            &[],
            &["com.tencent.weworkmac"],
            &["wxwork", "wxwork.exe"],
        ),
        reference(
            "message.messages",
            PersonalChat,
            "Messages",
            "messages",
            None,
            &[],
            &[],
            &["com.apple.mobilesms"],
            &["messages"],
        ),
        reference(
            "message.whatsapp",
            PersonalChat,
            "WhatsApp",
            "whatsapp",
            None,
            &["web.whatsapp.com"],
            &[],
            &["net.whatsapp.whatsapp"],
            &["whatsapp", "whatsapp.exe"],
        ),
        reference(
            "message.telegram",
            PersonalChat,
            "Telegram",
            "telegram",
            None,
            &["web.telegram.org"],
            &[],
            &["ru.keepcoder.telegram"],
            &["telegram", "telegram.exe"],
        ),
        reference(
            "message.wechat",
            PersonalChat,
            "WeChat",
            "wechat",
            None,
            &[],
            &[],
            &["com.tencent.xinwechat"],
            &["wechat", "wechat.exe"],
        ),
        reference(
            "doc.google_docs",
            Document,
            "Google Docs",
            "google-docs",
            None,
            &["docs.google.com"],
            &[],
            &[],
            &[],
        ),
        reference(
            "doc.notion",
            Document,
            "Notion",
            "notion",
            None,
            &[],
            &["notion.so"],
            &["notion.id"],
            &["notion", "notion.exe"],
        ),
        reference(
            "doc.word",
            Document,
            "Microsoft Word",
            "word",
            None,
            &[],
            &[],
            &["com.microsoft.word"],
            &["winword.exe", "microsoft word"],
        ),
        reference(
            "doc.wps",
            Document,
            "WPS Office",
            "wps",
            None,
            &[],
            &[],
            &["com.kingsoft.wpsoffice.mac"],
            &["wps", "wps.exe", "wpsoffice.exe"],
        ),
        reference(
            "doc.confluence",
            Document,
            "Confluence",
            "confluence",
            None,
            &[],
            &[],
            &[],
            &[],
        )
        .with_title_marker(TitleMarkerDefinition::for_host(
            " - Confluence",
            "atlassian.net",
        )),
        reference(
            "doc.yuque",
            Document,
            "Yuque",
            "yuque",
            None,
            &[],
            &["yuque.com"],
            &[],
            &[],
        ),
        reference(
            "project.linear",
            ProjectManagement,
            "Linear",
            "linear",
            Some("linear"),
            &[],
            &["linear.app"],
            &["com.linear"],
            &["linear", "linear.exe"],
        ),
        reference(
            "project.jira",
            ProjectManagement,
            "Jira",
            "jira",
            Some("jira"),
            &[],
            &[],
            &[],
            &[],
        )
        .with_title_marker(TitleMarkerDefinition::for_host(" - Jira", "atlassian.net")),
        reference(
            "project.figma",
            ProjectManagement,
            "Figma",
            "figma",
            Some("figma"),
            &[],
            &["figma.com"],
            &["com.figma.desktop"],
            &["figma", "figma.exe"],
        ),
        reference(
            "dev.github",
            DeveloperCollaboration,
            "GitHub",
            "github",
            Some("github"),
            &[],
            &["github.com"],
            &["com.github.githubclient"],
            &["github desktop", "githubdesktop.exe"],
        ),
        reference(
            "dev.gitlab",
            DeveloperCollaboration,
            "GitLab",
            "gitlab",
            Some("gitlab"),
            &[],
            &["gitlab.com"],
            &[],
            &[],
        ),
        reference(
            "code.cursor",
            PromptOrCode,
            "Cursor",
            "cursor",
            None,
            &[],
            &[],
            &["com.todesktop.230313mzl4w4u92"],
            &["cursor", "cursor.exe"],
        ),
        reference(
            "code.vscode",
            PromptOrCode,
            "Visual Studio Code",
            "vscode",
            None,
            &[],
            &[],
            &["com.microsoft.vscode", "com.microsoft.vscodeinsiders"],
            &["code", "code.exe"],
        ),
        reference(
            "code.jetbrains",
            PromptOrCode,
            "JetBrains IDE",
            "jetbrains",
            None,
            &[],
            &[],
            &["com.jetbrains.intellij", "com.jetbrains.pycharm"],
            &[
                "idea",
                "idea64.exe",
                "pycharm",
                "pycharm64.exe",
                "webstorm64.exe",
            ],
        ),
        reference(
            "prompt.chatgpt",
            PromptOrCode,
            "ChatGPT",
            "chatgpt",
            Some("chatgpt"),
            &[],
            &["chatgpt.com"],
            &["com.openai.chat"],
            &["chatgpt", "chatgpt.exe"],
        ),
        reference(
            "prompt.claude",
            PromptOrCode,
            "Claude",
            "claude",
            Some("claude"),
            &[],
            &["claude.ai"],
            &["com.anthropic.claudefordesktop"],
            &["claude", "claude.exe"],
        ),
        reference(
            "prompt.gemini",
            PromptOrCode,
            "Gemini",
            "gemini",
            None,
            &["gemini.google.com"],
            &[],
            &[],
            &[],
        ),
        reference(
            "support.zendesk",
            Support,
            "Zendesk",
            "zendesk",
            Some("zendesk"),
            &[],
            &["zendesk.com"],
            &[],
            &[],
        ),
        reference(
            "support.intercom",
            Support,
            "Intercom",
            "intercom",
            Some("intercom"),
            &["app.intercom.com"],
            &[],
            &[],
            &[],
        ),
        reference(
            "social.linkedin",
            Social,
            "LinkedIn",
            "linkedin",
            Some("linkedin"),
            &[],
            &["linkedin.com"],
            &[],
            &[],
        ),
        reference(
            "social.x",
            Social,
            "X",
            "x",
            Some("x"),
            &[],
            &["x.com"],
            &[],
            &[],
        ),
        extended(
            "email.spark",
            Email,
            "Spark",
            "email",
            &[],
            &[],
            &["com.readdle.smartemail-mac"],
            &["spark", "spark desktop.exe"],
        ),
        extended(
            "email.superhuman",
            Email,
            "Superhuman",
            "email",
            &[],
            &["superhuman.com"],
            &[],
            &[],
        ),
        extended(
            "email.thunderbird",
            Email,
            "Thunderbird",
            "email",
            &[],
            &[],
            &["org.mozilla.thunderbird"],
            &["thunderbird", "thunderbird.exe"],
        ),
        extended(
            "chat.mattermost",
            WorkChat,
            "Mattermost",
            "work-chat",
            &[],
            &[],
            &["com.mattermost.desktop"],
            &["mattermost", "mattermost.exe"],
        ),
        extended(
            "chat.rocket_chat",
            WorkChat,
            "Rocket.Chat",
            "work-chat",
            &[],
            &[],
            &["chat.rocket.desktop"],
            &["rocket.chat", "rocket.chat.exe"],
        ),
        extended(
            "chat.zoom",
            WorkChat,
            "Zoom Team Chat",
            "work-chat",
            &[],
            &[],
            &["us.zoom.xos"],
            &["zoom", "zoom.exe"],
        ),
        extended(
            "message.signal",
            PersonalChat,
            "Signal",
            "personal-chat",
            &[],
            &[],
            &["org.whispersystems.signal-desktop"],
            &["signal", "signal.exe"],
        ),
        extended(
            "message.discord",
            PersonalChat,
            "Discord",
            "personal-chat",
            &[],
            &["discord.com"],
            &["com.hnc.discord"],
            &["discord", "discord.exe"],
        ),
        extended(
            "message.qq",
            PersonalChat,
            "QQ",
            "personal-chat",
            &[],
            &[],
            &["com.tencent.qq"],
            &["qq", "qq.exe"],
        ),
        extended(
            "doc.pages",
            Document,
            "Pages",
            "document",
            &[],
            &[],
            &["com.apple.iwork.pages"],
            &["pages"],
        ),
        extended(
            "doc.obsidian",
            Document,
            "Obsidian",
            "document",
            &[],
            &[],
            &["md.obsidian"],
            &["obsidian", "obsidian.exe"],
        ),
        extended(
            "doc.craft",
            Document,
            "Craft",
            "document",
            &[],
            &[],
            &["com.lukilabs.lukiapp"],
            &["craft", "craft.exe"],
        ),
        extended(
            "doc.coda",
            Document,
            "Coda",
            "document",
            &[],
            &["coda.io"],
            &[],
            &[],
        ),
        extended(
            "doc.tencent_docs",
            Document,
            "Tencent Docs",
            "document",
            &["docs.qq.com"],
            &[],
            &[],
            &[],
        ),
        extended(
            "doc.shimo",
            Document,
            "Shimo",
            "document",
            &[],
            &["shimo.im"],
            &[],
            &[],
        ),
        extended(
            "doc.dropbox_paper",
            Document,
            "Dropbox Paper",
            "document",
            &["paper.dropbox.com"],
            &[],
            &[],
            &[],
        ),
        extended(
            "project.asana",
            ProjectManagement,
            "Asana",
            "project-management",
            &[],
            &["asana.com"],
            &[],
            &[],
        ),
        extended(
            "project.trello",
            ProjectManagement,
            "Trello",
            "project-management",
            &[],
            &["trello.com"],
            &[],
            &[],
        ),
        extended(
            "project.clickup",
            ProjectManagement,
            "ClickUp",
            "project-management",
            &[],
            &["clickup.com"],
            &[],
            &[],
        ),
        extended(
            "project.monday",
            ProjectManagement,
            "monday.com",
            "project-management",
            &[],
            &["monday.com"],
            &[],
            &[],
        ),
        extended(
            "project.todoist",
            ProjectManagement,
            "Todoist",
            "project-management",
            &[],
            &["todoist.com"],
            &["com.todoist.mac.todoist"],
            &["todoist", "todoist.exe"],
        ),
        extended(
            "project.things",
            ProjectManagement,
            "Things",
            "project-management",
            &[],
            &[],
            &["com.culturedcode.thingsmac"],
            &["things3"],
        ),
        extended(
            "dev.bitbucket",
            DeveloperCollaboration,
            "Bitbucket",
            "developer-collaboration",
            &[],
            &["bitbucket.org"],
            &[],
            &[],
        ),
        extended(
            "dev.azure_devops",
            DeveloperCollaboration,
            "Azure DevOps",
            "developer-collaboration",
            &[],
            &["dev.azure.com"],
            &[],
            &[],
        ),
        extended(
            "code.xcode",
            PromptOrCode,
            "Xcode",
            "prompt-code",
            &[],
            &[],
            &["com.apple.dt.xcode"],
            &["xcode"],
        ),
        extended(
            "code.zed",
            PromptOrCode,
            "Zed",
            "prompt-code",
            &[],
            &[],
            &["dev.zed.zed"],
            &["zed", "zed.exe"],
        ),
        extended(
            "code.sublime_text",
            PromptOrCode,
            "Sublime Text",
            "prompt-code",
            &[],
            &[],
            &["com.sublimetext.4"],
            &["sublime_text", "sublime_text.exe"],
        ),
        extended(
            "code.android_studio",
            PromptOrCode,
            "Android Studio",
            "prompt-code",
            &[],
            &[],
            &["com.google.android.studio"],
            &["studio64.exe", "android studio"],
        ),
        extended(
            "prompt.perplexity",
            PromptOrCode,
            "Perplexity",
            "prompt-code",
            &[],
            &["perplexity.ai"],
            &[],
            &[],
        ),
        extended(
            "prompt.copilot",
            PromptOrCode,
            "Microsoft Copilot",
            "prompt-code",
            &["copilot.microsoft.com"],
            &[],
            &[],
            &[],
        ),
        extended(
            "prompt.grok",
            PromptOrCode,
            "Grok",
            "prompt-code",
            &[],
            &["grok.com"],
            &[],
            &[],
        ),
        extended(
            "support.freshdesk",
            Support,
            "Freshdesk",
            "support",
            &[],
            &["freshdesk.com"],
            &[],
            &[],
        ),
        extended(
            "support.salesforce",
            Support,
            "Salesforce Service Cloud",
            "support",
            &["service.salesforce.com"],
            &[],
            &[],
            &[],
        ),
        extended(
            "support.hubspot",
            Support,
            "HubSpot Service",
            "support",
            &["app.hubspot.com"],
            &[],
            &[],
            &[],
        ),
        extended(
            "social.reddit",
            Social,
            "Reddit",
            "social",
            &[],
            &["reddit.com"],
            &[],
            &[],
        ),
        extended(
            "doc.medium",
            Document,
            "Medium",
            "document",
            &[],
            &["medium.com"],
            &[],
            &[],
        ),
        extended(
            "doc.substack",
            Document,
            "Substack",
            "document",
            &[],
            &["substack.com"],
            &[],
            &[],
        ),
        extended(
            "doc.wordpress",
            Document,
            "WordPress",
            "document",
            &[],
            &["wordpress.com"],
            &[],
            &[],
        ),
    ]
}

pub fn style_override(id: &str) -> Option<AppStyleOverride> {
    use ArtifactKind::*;
    use Density::*;
    use Formality::*;
    use ListBehavior::*;
    use MarkupPolicy::*;

    let value = match id {
        "gmail" | "outlook" => AppStyleOverride {
            artifact_kind: Email,
            formality: Professional,
            density: Balanced,
            markup: PlainText,
            list_behavior: NumberWhenExplicit,
        },
        "slack" => AppStyleOverride {
            artifact_kind: Message,
            formality: Casual,
            density: Compact,
            markup: PlainText,
            list_behavior: LineBreaks,
        },
        "teams" | "lark" => AppStyleOverride {
            artifact_kind: Message,
            formality: Neutral,
            density: Compact,
            markup: PlainText,
            list_behavior: LineBreaks,
        },
        "linear" | "figma" => AppStyleOverride {
            artifact_kind: TaskUpdate,
            formality: Neutral,
            density: Compact,
            markup: Light,
            list_behavior: Preserve,
        },
        "jira" => AppStyleOverride {
            artifact_kind: TaskUpdate,
            formality: Professional,
            density: Balanced,
            markup: Light,
            list_behavior: NumberWhenExplicit,
        },
        "github" | "gitlab" => AppStyleOverride {
            artifact_kind: DeveloperNote,
            formality: Neutral,
            density: Compact,
            markup: Light,
            list_behavior: Preserve,
        },
        "chatgpt" | "claude" => AppStyleOverride {
            artifact_kind: Prompt,
            formality: Neutral,
            density: Balanced,
            markup: Structured,
            list_behavior: NumberWhenExplicit,
        },
        "zendesk" => AppStyleOverride {
            artifact_kind: SupportReply,
            formality: Professional,
            density: Balanced,
            markup: PlainText,
            list_behavior: NumberWhenExplicit,
        },
        "intercom" => AppStyleOverride {
            artifact_kind: SupportReply,
            formality: Neutral,
            density: Compact,
            markup: PlainText,
            list_behavior: LineBreaks,
        },
        "linkedin" => AppStyleOverride {
            artifact_kind: SocialPost,
            formality: Professional,
            density: Balanced,
            markup: PlainText,
            list_behavior: Preserve,
        },
        "x" => AppStyleOverride {
            artifact_kind: SocialPost,
            formality: Casual,
            density: Compact,
            markup: PlainText,
            list_behavior: Preserve,
        },
        _ => return None,
    };
    Some(value)
}
