name: Bug Report
description: Report a bug to help us improve OpenTypeless
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: OpenTypeless Version
      placeholder: e.g. v0.1.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 11
        - Windows 10
        - macOS 15 (Sequoia)
        - macOS 14 (Sonoma)
        - Ubuntu 24.04
        - Other Linux
    validations:
      required: true
  - type: dropdown
    id: stt_provider
    attributes:
      label: STT Provider
      options:
        - Deepgram
        - AssemblyAI
        - OpenAI Whisper
        - Groq Whisper
        - GLM-ASR
        - SiliconFlow
        - Cloud (Pro)
        - N/A
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste relevant log output or attach screenshots.
      render: shell
