name: Feature Request
description: Suggest an idea for OpenTypeless
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? Why is the current behavior insufficient?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the desired behavior or API/UX.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, links to prior art, or other references.
